## OpenAI API Key

In [4]:
# Load OPENAI API KEY
import os
from google.colab import userdata
api_key = userdata.get('OPENAI_API_KEY')
os.environ["OPENAI_API_KEY"] = api_key

## Classical Metrics (BLEU / ROUGE)

In [2]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.6 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [3]:
!pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.1)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=04a31ef13fb3582a898330a36262c549fe6d41e120f74bde7039277ed9f9b1b3
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [4]:
import evaluate

bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

In [5]:
def evaluate_generation(gt_answers, predictions):
    bleu_score = bleu.compute(
        predictions=predictions,
        references=[[a] for a in gt_answers]
    )
    rouge_score = rouge.compute(
        predictions=predictions,
        references=gt_answers
    )
    return {
        "bleu": bleu_score["bleu"],
        "rougeL": rouge_score["rougeL"]
    }

In [6]:
evaluate_generation(["The sky color is blue"], ["Colour of sky is not red but blue"])

{'bleu': 0.0, 'rougeL': np.float64(0.4615384615384615)}

## RAGAS Evaluation Pipeline

[Reseach-Paper](https://arxiv.org/abs/2309.15217)

[Official-Website](https://www.ragas.io/)

[Github](https://github.com/vibrantlabsai/ragas)

In [7]:
!pip install ragas

Collecting ragas
  Downloading ragas-0.4.3-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.0.2)
Requirement already satisfied: datasets>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (4.0.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from ragas) (0.12.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.12.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ragas) (1.6.0)
Collecting appdirs (from ragas)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting diskcache>=5.6.3 (from ragas)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from ragas) (0.21.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from ragas) (13.9.4)
Requirement already satisfied: openai>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ragas) (4.67.1)
Collecting instructor (from ragas)
  Downloading instructor-1.14.4-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (11.3.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from ragas) (3.6.1)
Collecting scikit-network (from ragas)
  Downloading scikit_network-0.33.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (from ragas) (1.2.4)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (from ragas) (1.2.7)
Collecting langchain-community (from ragas)
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain_openai (from ragas)
  Downloading langchain_openai-1.1.7-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (3.20.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=4.0.0->ragas) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (6.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (0.12.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (0.4.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (3.13.3)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (0.17.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (3.1.6)
Collecting jiter<1,>=0.10.0 (from openai>=1.0.0->ragas)
  Downloading jiter-0.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Collecting pre-commit>=4.3.0 (from instructor->ragas)
  Downloading pre_commit-4.5.1-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (9.1.2)
Collecting ty>=0.0.1a23 (from instructor->ragas)
  Downloading ty-0.0.14-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.3 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas) (2.19.2)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (1.5.4)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain->ragas) (1.0.6)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (0.6.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (0.13.0)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community->ragas)
  Downloading langchain_classic-1.0.1-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (2.0.45)
Collecting requests>=2.32.2 (from datasets>=4.0.0->ragas)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community->ragas)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (2.12.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (0.4.3)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->ragas) (2025.11.3)
Requirement already satisfied: scipy>=1.7.3 in /usr/local/lib/python3.12/dist-packages (from scikit-network->ragas) (1.16.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (1.22.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai>=1.0.0->ragas) (3.11)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai>=1.0.0->ragas) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai>=1.0.0->ragas) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>=1.0.0->ragas) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets>=4.0.0->ragas) (1.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas) (3.0.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas) (3.0.0)
Collecting langchain-text-splitters<2.0.0,>=1.1.0 (from langchain-classic<2.0.0,>=1.0.0->langchain-community->ragas)
  Downloading langchain_text_splitters-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain->ragas) (4.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain->ragas) (1.0.6)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain->ragas) (0.3.3)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (0.25.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->ragas) (0.1.2)
Collecting cfgv>=2.0.0 (from pre-commit>=4.3.0->instructor->ragas)
  Downloading cfgv-3.5.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting identify>=1.0.0 (from pre-commit>=4.3.0->instructor->ragas)
  Downloading identify-2.6.16-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting nodeenv>=0.11.1 (from pre-commit>=4.3.0->instructor->ragas)
  Downloading nodeenv-1.10.0-py2.py3-none-any.whl.metadata (24 kB)
Collecting virtualenv>=20.10.0 (from pre-commit>=4.3.0->instructor->ragas)
  Downloading virtualenv-20.36.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.0.0->ragas) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.0.0->ragas) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community->ragas) (3.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.0.0->ragas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.0.0->ragas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.0.0->ragas) (2025.3)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain->ragas) (1.12.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.0.0->ragas) (1.17.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting distlib<1,>=0.3.7 (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor->ragas)
  Downloading distlib-0.4.0-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor->ragas) (4.5.1)
Downloading ragas-0.4.3-py3-none-any.whl (466 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.5/466.5 kB 14.4 MB/s eta 0:00:00
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 1.9 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading instructor-1.14.4-py3-none-any.whl (176 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.9/176.9 kB 10.3 MB/s eta 0:00:00
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 55.7 MB/s eta 0:00:00
Downloading langchain_openai-1.1.7-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 7.7 MB/s eta 0:00:00
Downloading scikit_network-0.33.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 70.8 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading jiter-0.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (358 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.8/358.8 kB 14.0 MB/s eta 0:00:00
Downloading langchain_classic-1.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 38.4 MB/s eta 0:00:00
Downloading pre_commit-4.5.1-py2.py3-none-any.whl (226 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.4/226.4 kB 15.1 MB/s eta 0:00:00
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 1.9 MB/s eta 0:00:00
Downloading ty-0.0.14-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 71.4 MB/s eta 0:00:00
Downloading cfgv-3.5.0-py2.py3-none-any.whl (7.4 kB)
Downloading identify-2.6.16-py2.py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 kB 8.3 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.0-py3-none-any.whl (34 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 3.3 MB/s eta 0:00:00
Downloading nodeenv-1.10.0-py2.py3-none-any.whl (23 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading virtualenv-20.36.1-py3-none-any.whl (6.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 77.2 MB/s eta 0:00:00
Downloading distlib-0.4.0-py2.py3-none-any.whl (469 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 kB 30.4 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: distlib, appdirs, virtualenv, ty, requests, nodeenv, mypy-extensions, marshmallow, jiter, identify, diskcache, cfgv, typing-inspect, scikit-network, pre-commit, dataclasses-json, instructor, langchain-text-splitters, langchain_openai, langchain-classic, langchain-community, ragas
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: jiter
    Found existing installation: jiter 0.12.0
    Uninstalling jiter-0.12.0:
      Successfully uninstalled jiter-0.12.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
Successfully installed appdirs-1.4.4 cfgv-3.5.0 dataclasses-json-0.6.7 diskcache-5.6.3 distlib-0.4.0 identify-2.6.16 instructor-1.14.4 jiter-0.11.1 langchain-classic-1.0.1 langchain-community-0.4.1 langchain-text-splitters-1.1.0 langchain_openai-1.1.7 marshmallow-3.26.2 mypy-extensions-1.1.0 nodeenv-1.10.0 pre-commit-4.5.1 ragas-0.4.3 requests-2.32.5 scikit-network-0.33.5 ty-0.0.14 typing-inspect-0.9.0 virtualenv-20.36.1

In [3]:
!pip install git+https://github.com/vibrantlabsai/ragas

Collecting git+https://github.com/vibrantlabsai/ragas
  Cloning https://github.com/vibrantlabsai/ragas to /tmp/pip-req-build-j71jkohh
  Running command git clone --filter=blob:none --quiet https://github.com/vibrantlabsai/ragas /tmp/pip-req-build-j71jkohh
  Resolved https://github.com/vibrantlabsai/ragas to commit f5f62387c501cc44ecd56b7765d4c4bfeeffe5a4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (2.0.2)
Requirement already satisfied: datasets>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (4.0.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (0.12.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (2.12.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (1.6.0)
Requirement already satisfied: appdirs in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (1.4.4)
Requirement already satisfied: diskcache>=5.6.3 in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (5.6.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (0.21.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (13.9.4)
Requirement already satisfied: openai>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (2.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (4.67.1)
Requirement already satisfied: instructor in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (1.14.4)
Requirement already satisfied: pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (11.3.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (3.6.1)
Requirement already satisfied: scikit-network in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (0.33.5)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (1.2.4)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (1.2.7)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (0.4.1)
Requirement already satisfied: langchain_openai in /usr/local/lib/python3.12/dist-packages (from ragas==0.4.4.dev6+gf5f62387c) (1.1.7)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (3.20.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (2.32.5)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (6.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (0.11.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas==0.4.4.dev6+gf5f62387c) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas==0.4.4.dev6+gf5f62387c) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas==0.4.4.dev6+gf5f62387c) (0.4.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas==0.4.4.dev6+gf5f62387c) (3.13.3)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas==0.4.4.dev6+gf5f62387c) (0.17.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas==0.4.4.dev6+gf5f62387c) (3.1.6)
Requirement already satisfied: pre-commit>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas==0.4.4.dev6+gf5f62387c) (4.5.1)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas==0.4.4.dev6+gf5f62387c) (9.1.2)
Requirement already satisfied: ty>=0.0.1a23 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas==0.4.4.dev6+gf5f62387c) (0.0.14)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas==0.4.4.dev6+gf5f62387c) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas==0.4.4.dev6+gf5f62387c) (2.19.2)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer->ragas==0.4.4.dev6+gf5f62387c) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->ragas==0.4.4.dev6+gf5f62387c) (1.5.4)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain->ragas==0.4.4.dev6+gf5f62387c) (1.0.6)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas==0.4.4.dev6+gf5f62387c) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas==0.4.4.dev6+gf5f62387c) (0.6.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas==0.4.4.dev6+gf5f62387c) (0.13.0)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas==0.4.4.dev6+gf5f62387c) (1.0.1)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas==0.4.4.dev6+gf5f62387c) (2.0.45)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas==0.4.4.dev6+gf5f62387c) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas==0.4.4.dev6+gf5f62387c) (2.12.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas==0.4.4.dev6+gf5f62387c) (0.4.3)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->ragas==0.4.4.dev6+gf5f62387c) (2025.11.3)
Requirement already satisfied: scipy>=1.7.3 in /usr/local/lib/python3.12/dist-packages (from scikit-network->ragas==0.4.4.dev6+gf5f62387c) (1.16.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas==0.4.4.dev6+gf5f62387c) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas==0.4.4.dev6+gf5f62387c) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas==0.4.4.dev6+gf5f62387c) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas==0.4.4.dev6+gf5f62387c) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas==0.4.4.dev6+gf5f62387c) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas==0.4.4.dev6+gf5f62387c) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas==0.4.4.dev6+gf5f62387c) (1.22.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (3.11)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas==0.4.4.dev6+gf5f62387c) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas==0.4.4.dev6+gf5f62387c) (0.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>=1.0.0->ragas==0.4.4.dev6+gf5f62387c) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (1.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas==0.4.4.dev6+gf5f62387c) (3.0.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas==0.4.4.dev6+gf5f62387c) (3.0.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community->ragas==0.4.4.dev6+gf5f62387c) (1.1.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain->ragas==0.4.4.dev6+gf5f62387c) (4.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain->ragas==0.4.4.dev6+gf5f62387c) (1.0.6)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain->ragas==0.4.4.dev6+gf5f62387c) (0.3.3)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas==0.4.4.dev6+gf5f62387c) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas==0.4.4.dev6+gf5f62387c) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas==0.4.4.dev6+gf5f62387c) (0.25.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->ragas==0.4.4.dev6+gf5f62387c) (0.1.2)
Requirement already satisfied: cfgv>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor->ragas==0.4.4.dev6+gf5f62387c) (3.5.0)
Requirement already satisfied: identify>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor->ragas==0.4.4.dev6+gf5f62387c) (2.6.16)
Requirement already satisfied: nodeenv>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor->ragas==0.4.4.dev6+gf5f62387c) (1.10.0)
Requirement already satisfied: virtualenv>=20.10.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor->ragas==0.4.4.dev6+gf5f62387c) (20.36.1)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas==0.4.4.dev6+gf5f62387c) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community->ragas==0.4.4.dev6+gf5f62387c) (3.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (2025.3)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain->ragas==0.4.4.dev6+gf5f62387c) (1.12.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.0.0->ragas==0.4.4.dev6+gf5f62387c) (1.17.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas==0.4.4.dev6+gf5f62387c) (1.1.0)
Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor->ragas==0.4.4.dev6+gf5f62387c) (0.4.0)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor->ragas==0.4.4.dev6+gf5f62387c) (4.5.1)
Building wheels for collected packages: ragas
  Building wheel for ragas (pyproject.toml) ... done
  Created wheel for ragas: filename=ragas-0.4.4.dev6+gf5f62387c-py3-none-any.whl size=467078 sha256=c0f898bc3c3050267ca6c8cfd595e012792c0ae11182f7819fc20151f21c2495
  Stored in directory: /tmp/pip-ephem-wheel-cache-_j32opfl/wheels/b1/27/dd/e75da40deb69b2bf020c19d7ac497031b6bebdc90e976c143e
Successfully built ragas
Installing collected packages: ragas
  Attempting uninstall: ragas
    Found existing installation: ragas 0.4.3
    Uninstalling ragas-0.4.3:
      Successfully uninstalled ragas-0.4.3
Successfully installed ragas-0.4.4.dev6+gf5f62387c

### AnswerRelevancy

In [17]:
AnswerRelevancy

ragas.metrics.collections.answer_relevancy.metric.AnswerRelevancy

In [1]:
from ragas import evaluate
from ragas.metrics.collections import (AnswerRelevancy,
                                       Faithfulness,
                                       ContextPrecision,
                                       ContextRecall)

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

In [2]:
import openai
from ragas.llms.base import llm_factory
from ragas.embeddings.base import embedding_factory

In [5]:
# Setup dependencies

client = openai.AsyncOpenAI()

llm = llm_factory("gpt-4o-mini",
                  client=client)

embeddings = embedding_factory("openai",
                               model="text-embedding-3-large",
                               client=client)

In [6]:
# Create metric instance
metric = AnswerRelevancy(llm=llm, embeddings=embeddings, strictness=3)
# Single evaluation
result = await metric.ascore(
user_input="What is the capital of France?",
response="Paris is the capital of France.")

print(f"Answer Relevancy: {result.value}")

Answer Relevancy: 0.9999996014852707

### Faithfulness

In [15]:
Faithfulness

ragas.metrics.collections.faithfulness.metric.Faithfulness

In [16]:
import instructor

# Create metric instance
metric = Faithfulness(llm=llm)

# Single evaluation
result = await metric.ascore(
    user_input="Where was Einstein born?",
    response="Einstein was born in Germany on 14th March 1879.",
    retrieved_contexts=["Albert Einstein was born in Germany..."]
    )

print(f"Faithfulness Score: {result.value}")

Faithfulness Score: 0.5

### ContextPrecision

In [18]:
ContextPrecision

ragas.metrics.collections.context_precision.metric.ContextPrecision

In [19]:
# Create metric instance (same as ContextPrecisionWithReference)
metric = ContextPrecision(llm=llm)

# Single evaluation
result = await metric.ascore(
    user_input="What is the capital of France?",
    reference="Paris is the capital of France.",
    retrieved_contexts=["Paris is the capital and largest city of France."]
    )

In [20]:
print(f"ContextPrecision Score: {result.value}")

ContextPrecision Score: 0.9999999999

### ContextRecall

- Evaluates context recall by classifying if statements in a reference answer can be attributed to the retrieved context. Uses an LLM to verify attribution for each statement and calculates recall as the proportion of attributed statements.

In [21]:
ContextRecall

ragas.metrics.collections.context_recall.metric.ContextRecall

In [22]:
metric = ContextRecall(llm=llm)

# Single evaluation
result = await metric.ascore(
    user_input="What is the capital of France?",
    retrieved_contexts=["Paris is the capital of France."],
    reference="Paris is the capital and largest city of France."
    )

print(f"Context Recall: {result.value}")

Context Recall: 0.9999999999

### Summarization Score

In [7]:
from ragas.metrics import summarization_score
# from ragas.metrics.collections import summarization_score
from ragas import evaluate
from datasets import Dataset


data_samples = {
    'contexts':[["A company is launching a new product, a smartphone app designed to help users track their fitness goals. The app allows users to set daily exercise targets, log their meals, and track their water intake. It also provides personalized workout recommendations and sends motivational reminders throughout the day."]],

    'response':['A company is launching a fitness tracking app that helps users set exercise goals, log meals, and track water intake, with personalized workout suggestions and motivational reminders.'],

    'reference_contexts':[[
        "A company is launching a new product, a smartphone app designed to help users track their fitness goals."

    ]]


}
dataset = Dataset.from_dict(data_samples)
score = evaluate(dataset,metrics=[summarization_score])
score.to_pandas()

/tmp/ipython-input-3074370762.py:1: DeprecationWarning: Importing summarization_score from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import summarization_score
  from ragas.metrics import summarization_score

Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

,retrieved_contexts,reference_contexts,response,summary_score
0,"[A company is launching a new product, a smart...","[A company is launching a new product, a smart...",A company is launching a fitness tracking app ...,0.333333

In [13]:
score

{'summary_score': 0.3333}

In [12]:
score["summary_score"][0]

0.3333333333338141

### RAGS Evaluation Pipeline

In [ ]:
import openai
import evaluate as ev
import instructor

from ragas import evaluate
from ragas.metrics.collections import (AnswerRelevancy,
                                       Faithfulness,
                                       ContextPrecision,
                                       ContextRecall)

from ragas.metrics import summarization_score
from datasets import Dataset
from ragas.llms.base import llm_factory
from ragas.embeddings.base import embedding_factory


bleu = ev.load("bleu")
rouge = ev.load("rouge")

def evaluate_generation(gt_answers, predictions):
    bleu_score = bleu.compute(
        predictions=predictions,
        references=[[a] for a in gt_answers]
    )
    rouge_score = rouge.compute(
        predictions=predictions,
        references=gt_answers
    )
    return {
        "bleu": bleu_score["bleu"],
        "rougeL": rouge_score["rougeL"]
    }


def ragas_answer_relevancy(user_input: str, response: str):


  # Setup dependencies
  client = openai.AsyncOpenAI()
  llm = llm_factory("gpt-4o-mini",
                  client=client)

  embeddings = embedding_factory("openai",
                               model="text-embedding-3-large",
                               client=client)
  # Create metric instance
  answer_relevancy_metric = AnswerRelevancy(llm=llm,
                                            embeddings=embeddings,
                                            strictness=3)
  # Single evaluation
  answer_relevancy_result = metric.ascore(user_input, response)

  return answer_relevancy_result.value


def ragas_faithfulness(user_input: str,
                       response: str,
                       retrieved_contexts: list):

  # Setup dependencies
  client = openai.AsyncOpenAI()
  llm = llm_factory("gpt-4o-mini",
                  client=client)

  # Create metric instance
  faithfulness_metric = Faithfulness(llm=llm)

  # Single evaluation
  faithfulness_result = faithfulness_metric.ascore(
      user_input=user_input,
      response=response,
      retrieved_contexts=retrieved_contexts
      )

  return faithfulness_result.value


def ragas_context_precision(user_input: str,
                            reference: str,
                            retrieved_contexts: list):

  # Setup dependencies
  client = openai.AsyncOpenAI()
  llm = llm_factory("gpt-4o-mini",
                  client=client)

  # Create metric instance (same as ContextPrecisionWithReference)
  precision_metric = ContextPrecision(llm=llm)

  # Single evaluation
  precision_result = precision_metric.ascore(
      user_input=user_input,
      reference=reference,
      retrieved_contexts=retrieved_contexts)

  return precision_result.value


def ragas_context_recall(user_input: str,
                         reference: str,
                         retrieved_contexts: list):

  # Setup dependencies
  client = openai.AsyncOpenAI()
  llm = llm_factory("gpt-4o-mini",
                  client=client)

  # Create metric instance
  recall_metric = ContextRecall(llm=llm)

  # Single evaluation
  recall_result = recall_metric.ascore(
      user_input=user_input,
      retrieved_contexts=retrieved_contexts,
      reference=reference
      )

  return recall_result.value


def ragas_summarization_score(contexts: list,
                              response: str,
                              reference_contexts: list):


  data_samples = {

      'contexts':contexts,

      'response':response,

      'reference_contexts':reference_contexts
      }


  dataset = Dataset.from_dict(data_samples)
  score = evaluate(dataset, metrics=[summarization_score])

  return score["summary_score"][0]

## Trulens

### Ground Truth Evaluations

In [32]:
!pip install trulens trulens-providers-openai

Collecting trulens
  Downloading trulens-2.5.3-py3-none-any.whl.metadata (4.1 kB)
Collecting trulens-providers-openai
  Downloading trulens_providers_openai-2.5.3-py3-none-any.whl.metadata (1.1 kB)
Collecting trulens-core<3.0.0,>=2.0.0 (from trulens)
  Downloading trulens_core-2.5.3-py3-none-any.whl.metadata (1.6 kB)
Collecting trulens-dashboard<3.0.0,>=2.0.0 (from trulens-dashboard[full]<3.0.0,>=2.0.0->trulens)
  Downloading trulens_dashboard-2.5.3-py3-none-any.whl.metadata (1.6 kB)
Collecting trulens-feedback<3.0.0,>=2.0.0 (from trulens)
  Downloading trulens_feedback-2.5.3-py3-none-any.whl.metadata (17 kB)
Collecting trulens-otel-semconv<3.0.0,>=2.0.0 (from trulens)
  Downloading trulens_otel_semconv-2.5.3-py3-none-any.whl.metadata (1.1 kB)
Collecting trulens_eval<3.0.0,>=2.0.0 (from trulens)
  Downloading trulens_eval-2.5.3-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: langchain-community>=0.3.29 in /usr/local/lib/python3.12/dist-packages (from trulens-providers-openai) (0.4.1)
Collecting openai<2.0.0,>=1.52.1 (from trulens-providers-openai)
  Downloading openai-1.109.1-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (1.2.7)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (1.0.1)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (2.0.45)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (9.1.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (2.12.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (0.6.4)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.29->trulens-providers-openai) (2.0.2)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.52.1->trulens-providers-openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.52.1->trulens-providers-openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.52.1->trulens-providers-openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.52.1->trulens-providers-openai) (0.11.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.52.1->trulens-providers-openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.52.1->trulens-providers-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.52.1->trulens-providers-openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.52.1->trulens-providers-openai) (4.15.0)
Requirement already satisfied: alembic<2.0.0,>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (1.18.1)
Requirement already satisfied: dill<0.4.0,>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (0.3.8)
Requirement already satisfied: importlib-resources<7.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (6.5.2)
Collecting munch<3.0.0,>=2.5.0 (from trulens-core<3.0.0,>=2.0.0->trulens)
  Downloading munch-2.5.0-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: nest-asyncio<2.0,>=1.5 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (1.6.0)
Requirement already satisfied: opentelemetry-api>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (1.37.0)
Requirement already satisfied: opentelemetry-proto>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (1.37.0)
Requirement already satisfied: opentelemetry-sdk>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (1.37.0)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (25.0)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (2.2.2)
Requirement already satisfied: python-dotenv<2.0,>=0.21 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (1.2.1)
Requirement already satisfied: rich<14.0.0,>=13.6.0 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (13.9.4)
Requirement already satisfied: wrapt>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from trulens-core<3.0.0,>=2.0.0->trulens) (2.0.1)
Requirement already satisfied: ipywidgets>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (7.7.1)
Collecting jupyter<2,>=1 (from trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens)
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: plotly<6.0.0,>=5.22.0 in /usr/local/lib/python3.12/dist-packages (from trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (5.24.1)
Requirement already satisfied: psutil<6.0,>=5.9 in /usr/local/lib/python3.12/dist-packages (from trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (5.9.5)
Collecting streamlit<2.0,>=1.35 (from trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens)
  Downloading streamlit-1.53.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: traitlets<6.0.0,>=5.0.5 in /usr/local/lib/python3.12/dist-packages (from trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (5.7.1)
Collecting streamlit-aggrid<1.1.8,>=1.0.5 (from trulens-dashboard[full]<3.0.0,>=2.0.0->trulens)
  Downloading streamlit_aggrid-1.1.7-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: nltk<4.0.0,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from trulens-feedback<3.0.0,>=2.0.0->trulens) (3.9.1)
Requirement already satisfied: scikit-learn<2.0.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trulens-feedback<3.0.0,>=2.0.0->trulens) (1.6.1)
Requirement already satisfied: scipy<2.0.0,>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from trulens-feedback<3.0.0,>=2.0.0->trulens) (1.16.3)
Requirement already satisfied: opentelemetry-semantic-conventions>=0.36b0 in /usr/local/lib/python3.12/dist-packages (from trulens-otel-semconv<3.0.0,>=2.0.0->trulens) (0.58b0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.29->trulens-providers-openai) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.29->trulens-providers-openai) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.29->trulens-providers-openai) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.29->trulens-providers-openai) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.29->trulens-providers-openai) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.29->trulens-providers-openai) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.29->trulens-providers-openai) (1.22.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic<2.0.0,>=1.8.1->trulens-core<3.0.0,>=2.0.0->trulens) (1.3.10)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.52.1->trulens-providers-openai) (3.11)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community>=0.3.29->trulens-providers-openai) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community>=0.3.29->trulens-providers-openai) (0.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.52.1->trulens-providers-openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.52.1->trulens-providers-openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<2.0.0,>=1.52.1->trulens-providers-openai) (0.16.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.1.2->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.1.2->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.1.2->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (3.6.10)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.1.2->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (7.34.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.1.2->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (3.0.16)
Requirement already satisfied: notebook in /usr/local/lib/python3.12/dist-packages (from jupyter<2,>=1->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (6.5.7)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.12/dist-packages (from jupyter<2,>=1->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (6.6.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.12/dist-packages (from jupyter<2,>=1->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (7.16.6)
Collecting jupyterlab (from jupyter<2,>=1->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens)
  Downloading jupyterlab-4.5.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community>=0.3.29->trulens-providers-openai) (1.1.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community>=0.3.29->trulens-providers-openai) (1.33)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community>=0.3.29->trulens-providers-openai) (0.13.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community>=0.3.29->trulens-providers-openai) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community>=0.3.29->trulens-providers-openai) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community>=0.3.29->trulens-providers-openai) (0.25.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from munch<3.0.0,>=2.5.0->trulens-core<3.0.0,>=2.0.0->trulens) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk<4.0.0,>=3.9.1->trulens-feedback<3.0.0,>=2.0.0->trulens) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk<4.0.0,>=3.9.1->trulens-feedback<3.0.0,>=2.0.0->trulens) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk<4.0.0,>=3.9.1->trulens-feedback<3.0.0,>=2.0.0->trulens) (2025.11.3)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.23.0->trulens-core<3.0.0,>=2.0.0->trulens) (8.7.1)
Requirement already satisfied: protobuf<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-proto>=1.23.0->trulens-core<3.0.0,>=2.0.0->trulens) (5.29.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->trulens-core<3.0.0,>=2.0.0->trulens) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->trulens-core<3.0.0,>=2.0.0->trulens) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->trulens-core<3.0.0,>=2.0.0->trulens) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai<2.0.0,>=1.52.1->trulens-providers-openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai<2.0.0,>=1.52.1->trulens-providers-openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai<2.0.0,>=1.52.1->trulens-providers-openai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community>=0.3.29->trulens-providers-openai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community>=0.3.29->trulens-providers-openai) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<14.0.0,>=13.6.0->trulens-core<3.0.0,>=2.0.0->trulens) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<14.0.0,>=13.6.0->trulens-core<3.0.0,>=2.0.0->trulens) (2.19.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.3.0->trulens-feedback<3.0.0,>=2.0.0->trulens) (3.6.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community>=0.3.29->trulens-providers-openai) (3.3.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (1.9.0)
Requirement already satisfied: cachetools<7,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (6.2.4)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (11.3.0)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (18.1.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (0.10.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (3.1.46)
Collecting pydeck<1,>=0.8.0b4 (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (6.5.1)
Collecting python-decouple (from streamlit-aggrid<1.1.8,>=1.0.5->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens)
  Downloading python_decouple-3.8-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit<2.0,>=1.35->trulens-dashboard<3.0.0,>=2.0.0->trulens-dashboard[full]<3.0.0,>=2.0.0->trulens) (2.15.0)

In [34]:
from trulens.core import TruSession

session = TruSession()

🦑 Initialized with db url sqlite:///default.sqlite .
🛑 Secret keys may be written to the database. See the `database_redact_keys` option of `TruSession` to prevent this.

Updating app_name and app_version in apps table: 0it [00:00, ?it/s]
Updating app_id in records table: 0it [00:00, ?it/s]
Updating app_json in apps table: 0it [00:00, ?it/s]

✅ experimental Feature.OTEL_TRACING enabled.
🔒 experimental Feature.OTEL_TRACING is enabled and cannot be changed.

WARNI [torchao.kernel.intmm] Warning: Detected no triton, on systems without Triton certain kernels will not work

In [35]:
# Create Simple LLM Application

from openai import OpenAI
from trulens.core.otel.instrument import instrument

oai_client = OpenAI()


class APP:
    @instrument()
    def completion(self, prompt):
        completion = (
            oai_client.chat.completions.create(
                model="gpt-3.5-turbo",
                temperature=0,
                messages=[
                    {
                        "role": "user",
                        "content": f"Please answer the question: {prompt}",
                    }
                ],
            )
            .choices[0]
            .message.content
        )
        return completion


llm_app = APP()

In [36]:
# Initialize Feedback Function(s)

from trulens.core import Feedback
from trulens.feedback import GroundTruthAgreement
from trulens.providers.openai import OpenAI as fOpenAI

golden_set = [
    {
        "query": "who invented the lightbulb?",
        "expected_response": "Thomas Edison",
    },
    {
        "query": "¿quien invento la bombilla?",
        "expected_response": "Thomas Edison",
    },
]

f_groundtruth = Feedback(
    GroundTruthAgreement(golden_set, provider=fOpenAI()).agreement_measure,
    name="Ground Truth Semantic Agreement",
).on_input_output()

In [39]:
# Instrument chain for logging with TruLens

# add trulens as a context manager for llm_app
from trulens.apps.app import TruApp

tru_app = TruApp(
    llm_app, app_name="LLM App", app_version="v1", feedbacks=[f_groundtruth]
)

# Instrumented query engine can operate as a context manager:
with tru_app as recording:
    llm_app.completion("¿quien invento la bombilla?")
    llm_app.completion("who invented the lightbulb?")

In [40]:
# See results

session.get_leaderboard(app_ids=[tru_app.app_id])

                      Ground Truth Semantic Agreement   latency  total_cost
app_name app_version
LLM App  v1                                       1.0  0.720703    0.000031

In [41]:
from trulens.dashboard import run_dashboard

run_dashboard(session=session)

Starting dashboard ...
npm warn exec The following package was not found and will be installed: localtunnel@2.0.2

Go to this url and submit the ip given here. your url is: https://beige-teams-love.loca.lt

  Submit this IP Address: 34.150.239.250