# Data Exploration and Preparation

## Dataset 3: COVID-FAQ / COUGH Dataset (SunLab, Ohio State University)

[Dataset3](https://github.com/sunlab-osu/covid-faq/tree/main/data)

### Data Description

#### **Dataset Origin and Context**

The COUGH (COVID-19 FAQ Retrieval) dataset is a well-established benchmark dataset designed specifically for FAQ retrieval and question answering tasks in the COVID-19 domain. It was introduced to support research in information retrieval, semantic matching, and public health question answering, particularly during the COVID-19 pandemic.
The FAQ_Bank.csv file represents the complete FAQ repository, containing 15,919 expert-curated FAQ items collected from authoritative health and government sources such as healthcare agencies, public health departments, and official medical organisations. Unlike conversational or forum-based data, this dataset focuses on non-forum, verified FAQ content, making it especially suitable for high-trust information systems.

#### **Dataset Structure**

The dataset consists of 9 columns, structured as follows:
- Column Name: Description
- index	Unique: identifier for each FAQ item
- url: Source URL of the FAQ
- question: COVID-19 related public health question
- original answer: Raw answer text (HTML-rich)
- answer wLink: Cleaned answer text with hyperlinks
- source: Publishing organisation (e.g., AHCCCS)
- language:	Language code (primarily English – en)
- type: Entry type (e.g., Question)

The dataset follows a Question–Answer (QA) structure, which aligns directly with the requirements of Retrieval-Augmented Generation (RAG) pipelines.

#### **Appropriateness for This Study**

This dataset is highly appropriate for your research for several reasons:
- Public Health Focus
  - All FAQs are framed for general users, not clinicians, aligning perfectly with your study’s emphasis on lay audiences.
- High Retrieval Complexity
  - Large FAQ bank (15k+ items)
  - Semantically overlapping questions
    → Ideal for evaluating advanced retrieval, re-ranking, and query optimisation
- Benchmark Relevance
  - COUGH is widely used in FAQ retrieval research, strengthening the academic credibility of your evaluation.
- RAG Compatibility
  - Clean QA pairs
  - Source attribution via URLs
  - Suitable for chunk-level citation grounding

### Statistical & Exploratory Analysis

In [1]:
# Import Required Libraries

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from typing import List, Dict

In [2]:
file_path3 = "/content/drive/MyDrive/MS-LJMU/Data/covid-faq-main/data/FAQ_Bank.csv"

In [3]:
df3 = pd.read_csv(file_path3)

In [4]:
df3.head()

,index,url,question,original answer,answer,answer wLink,source,language,type
0,0,https://www.azahcccs.gov/AHCCCS/AboutUs/covid1...,Does AHCCCS have a centralized resource for m...,"<dd><b>Answer: </b>Yes, the AHCCCS <a href=""/P...","Yes, the AHCCCS Medical Coding Resources webp...","Answer: Yes, the AHCCCS Medical Coding Resourc...",AHCCCS,en,Question
1,1,https://www.azahcccs.gov/AHCCCS/AboutUs/covid1...,Are there billing codes available for COVID-1...,<dd><b>Answer: </b>Yes. The Centers for Medica...,Yes. The Centers for Medicare & Medicaid Serv...,Answer: Yes. The Centers for Medicare & Medica...,AHCCCS,en,Question
2,2,https://www.azahcccs.gov/AHCCCS/AboutUs/covid1...,Will AHCCCS issue guidance regarding prior au...,<dd><b>Answer: </b>Prior authorization is not ...,Prior authorization is not permitted for COVI...,Answer: Prior authorization is not permitted f...,AHCCCS,en,Question
3,3,https://www.azahcccs.gov/AHCCCS/AboutUs/covid1...,Is there a claims modifier for services relat...,"<dd><b>Answer: </b>Yes, AHCCCS has designated ...","Yes, AHCCCS has designated the CR modifier to...","Answer: Yes, AHCCCS has designated the CR modi...",AHCCCS,en,Question
4,4,https://www.azahcccs.gov/AHCCCS/AboutUs/covid1...,Does AHCCCS cover testing for COVID-19?,"<dd><b>Answer: </b>Yes, AHCCCS covers COVID-19...","Yes, AHCCCS covers COVID-19 testing. HCPCS U0...","Answer: Yes, AHCCCS covers COVID-19 testing. H...",AHCCCS,en,Question

In [5]:
df3["language"].unique()

array(['en', 'es', 'ko', 'vi', 'zh', 'ar', 'fa', 'hy', 'kr', 'ja', 'fr',
       'ru', 'cs', 'de', 'hi', 'id', 'it', 'nl', 'pt', 'th'], dtype=object)

In [7]:
df3 = df3[df3["language"]=="en"] # Taking only english Q&A

In [9]:
df3 = df3.dropna() # Drop null values

In [10]:
# Basic Dataset Inspection


print("Dataset Shape:", df3.shape)

print("Columns:", df3.columns.tolist())

df3.isnull().sum()

Dataset Shape: (9148, 9)
Columns: ['index', 'url', 'question', 'original answer', 'answer', 'answer wLink', 'source', 'language', 'type']

index              0
url                0
question           0
original answer    0
answer             0
answer wLink       0
source             0
language           0
type               0
dtype: int64

In [11]:
df3["question"]

0        Does AHCCCS have a centralized resource for m...
1        Are there billing codes available for COVID-1...
2        Will AHCCCS issue guidance regarding prior au...
3        Is there a claims modifier for services relat...
4                 Does AHCCCS cover testing for COVID-19?
                              ...
9146    Am I High Risk for Covid19? I am a diabetic wh...
9147    Am I High Risk for Covid19? I am a diabetic wh...
9148    Am I High Risk for Covid19? I am a diabetic wh...
9149    Children and grandparents. \n            \n\n ...
9150    Children and grandparents. \n            \n\n ...
Name: question, Length: 9148, dtype: object

In [12]:
df3["answer wLink"]

0       Answer: Yes, the AHCCCS Medical Coding Resourc...
1       Answer: Yes. The Centers for Medicare & Medica...
2       Answer: Prior authorization is not permitted f...
3       Answer: Yes, AHCCCS has designated the CR modi...
4       Answer: Yes, AHCCCS covers COVID-19 testing. H...
                              ...
9146    Those who are higher risk of novel coronavirus...
9147    Gosh, I'm sorry you went through that.  I'm ve...
9148    Do you have any remaining issues from the seps...
9149    If you have any children or grandparents artic...
9150    One of the deaths in my state was a 14 year ol...
Name: answer wLink, Length: 9148, dtype: object

### Visualisations and Insights

# Embedding Preparation

In [21]:
EMBEDDING_MODEL = "text-embedding-3-large"
EMBEDDING_DIM = 3072

In [13]:
def build_embedding_text(row):
    return f"""Question: {row['question']}

Answer: {row['answer']}"""

In [14]:
!pip install langchain
!pip install openai
!pip install tiktoken

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.3)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.6)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.13.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.1)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.32.4)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (0.25.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.5.0)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.14.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (0.12.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (2026.1.4)

In [15]:
!pip install -U langchain-text-splitters

Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-text-splitters) (1.2.6)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (25.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (0.13.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (2.32.4)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (0.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.0->langchain-text-splitters) (2.5.0)
Downloading langchain_text_splitters-1.1.0-py3-none-any.whl (34 kB)
Installing collected packages: langchain-text-splitters
Successfully installed langchain-text-splitters-1.1.0

In [16]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [17]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)

In [18]:
def chunk_faq(row):
    chunks = splitter.split_text(row["answer"])
    documents = []

    for i, chunk in enumerate(chunks):
        text = f"""Question: {row['question']}

Answer (Part {i+1}): {chunk}"""
        documents.append((text, i))

    return documents

In [19]:
from langchain_core.documents import Document

In [20]:
documents = []

for _, row in df3.iterrows():
    chunks = chunk_faq(row)
    for text, chunk_id in chunks:
        metadata = {
            "faq_id": row["index"],
            "source": row["source"],
            "url": row["url"],
            "language": row["language"],
            "type": row["type"],
            "chunk_id": chunk_id,
            "dataset": "COUGH_FAQ"
        }

        documents.append(
            Document(
                page_content=text,
                metadata=metadata
            )
        )

In [22]:
import tiktoken

encoding = tiktoken.encoding_for_model(EMBEDDING_MODEL)

def count_tokens(text: str) -> int:
    """
    Count tokens for a given text using tiktoken.
    """
    return len(encoding.encode(text))


def add_token_metadata(documents):
    """
    Adds token count to each Document's metadata.
    """
    for doc in documents:
        doc.metadata["embedding_tokens"] = count_tokens(doc.page_content)
    return documents

In [23]:
documents = add_token_metadata(documents)

In [26]:
documents[5]

Document(metadata={'faq_id': 1, 'source': 'AHCCCS', 'url': 'https://www.azahcccs.gov/AHCCCS/AboutUs/covid19FAQ.html', 'language': 'en', 'type': 'Question', 'chunk_id': 4, 'dataset': 'COUGH_FAQ', 'embedding_tokens': 63}, page_content='Question:  Are there billing codes available for COVID-19 testing outside of Centers for Disease Control and Prevention (CDC) testing laboratories?\n\nAnswer (Part 5): that would otherwise be identified by U0002. Neither U0003 nor U0004 should be used for tests that detect COVID-19 antibodies.')

# Data Indexing (Embeddings)

### FAISS: Facebook AI Similarity Search

[Link](https://docs.langchain.com/oss/python/integrations/vectorstores/faiss)

In [28]:
from openai import OpenAI
from google.colab import userdata

In [29]:
api_key = userdata.get('OPENAI_API_KEY')

In [30]:
os.environ["OPENAI_API_KEY"] = api_key

In [31]:
client = OpenAI()

In [32]:
!pip install langchain_openai

Collecting langchain_openai
  Downloading langchain_openai-1.1.7-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.6 in /usr/local/lib/python3.12/dist-packages (from langchain_openai) (1.2.6)
Requirement already satisfied: openai<3.0.0,>=1.109.1 in /usr/local/lib/python3.12/dist-packages (from langchain_openai) (2.14.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain_openai) (0.12.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.6->langchain_openai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.6->langchain_openai) (0.6.1)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.6->langchain_openai) (25.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.6->langchain_openai) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.6->langchain_openai) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.6->langchain_openai) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.6->langchain_openai) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.6->langchain_openai) (0.13.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain_openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain_openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain_openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain_openai) (0.12.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain_openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain_openai) (4.67.1)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain_openai) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain_openai) (2.32.4)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai<3.0.0,>=1.109.1->langchain_openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=1.109.1->langchain_openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=1.109.1->langchain_openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<3.0.0,>=1.109.1->langchain_openai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.6->langchain_openai) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.6->langchain_openai) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.6->langchain_openai) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.6->langchain_openai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.6->langchain_openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.6->langchain_openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.6->langchain_openai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain_openai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain_openai) (2.5.0)
Downloading langchain_openai-1.1.7-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 2.9 MB/s eta 0:00:00
Installing collected packages: langchain_openai
Successfully installed langchain_openai-1.1.7

In [33]:
!pip install -qU langchain-community faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 29.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 38.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 41.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 3.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.

In [34]:
import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS

In [35]:
embeddings = OpenAIEmbeddings(model=EMBEDDING_MODEL)

In [36]:
index = faiss.IndexFlatL2(EMBEDDING_DIM)

vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

#### Add items to vector store

In [37]:
from uuid import uuid4

In [38]:
uuids = [str(uuid4()) for _ in range(len(documents))]

vector_store.add_documents(documents=documents, ids=uuids)

['69132eb2-66ad-41c3-88f7-782aa3727019',
 '1950903e-9259-459b-a627-3344321d00a4',
 'fdd5af07-1a28-4992-9600-e72467075c8d',
 '28787933-1ab9-4c63-adce-c7f0a21ba7fc',
 '4dfad708-2fa6-443b-adc5-8b96546f290a',
 '8db11a14-bcce-49df-b5b2-1d9b9d8c484d',
 '6743db54-5dff-44b7-91aa-525247d9c92e',
 'a59f2cc1-0121-4ae8-a33a-625ba24b4734',
 'dbfd662e-fbbb-417d-a94d-58c6ef3d1e9c',
 'ea5bab19-bb41-4962-bc3d-556b77a632e9',
 'e628f1e0-5e72-4613-9f4c-0afe2cfb01e4',
 '38d0289e-ef83-4318-85bd-c689f0a687cc',
 '47164fb7-db00-4a0e-86e4-674fd70d552f',
 'db63b15c-603f-4ecb-a47c-50a109377662',
 '3c715797-7a39-4769-806a-4ffe6cc1ea92',
 '8a67a447-23b7-4834-8e4a-0e5ea54903e9',
 '149fc1b2-2616-4375-8e3a-b402d2bb90e3',
 '96538bf7-d926-4b86-a2ec-1712bad2c004',
 'bdf07712-f769-481a-84e0-6efb1eca22cd',
 '3266d946-6ce9-4a43-8956-ab3cf8468fd1',
 '7bf0ba4b-5ba6-4fbd-96f0-21b77a71ebba',
 'c94c7708-37f3-4cc3-a0c8-a0b7b2ec9086',
 '4ef4526c-188d-49fb-a3ec-7291692958aa',
 'bfb75bb3-3bf6-4be4-b458-c56588d3ee90',
 '2b8a2f72-8726-4b83-bb35-0994e60b0568',
 '981bbd1c-c43f-40b6-8716-88b795044670',
 'cbe97592-6dab-4295-9cb3-cc338323265d',
 '61af8f15-244a-4e2c-aa50-69ad98efee81',
 'd7169299-cc74-4963-a6bf-4f556459fc52',
 'f53031c7-bae4-451c-ac98-bb2fcd9d64d4',
 '6b996a38-a777-4d11-8560-04d991587674',
 '7612824d-6072-44c8-b8fa-48a89a950108',
 'ed7841eb-1548-4e1c-93ff-43e1b62336d5',
 'c66fcafc-0b53-44c9-93e9-fc964ec22d06',
 'a832e06e-8ba5-49f2-a9d5-bee999eabcdd',
 '96033c23-50db-42e9-9a61-3c7bc52c1d6a',
 '0236c616-f9c2-46f3-99c6-55a1921c7de4',
 'ebca4bf1-73a2-4105-81a2-caf736230939',
 '4386b021-9e70-4f27-9367-edd8958fa4df',
 'ca38dc6d-1b3a-4254-91ea-e875dd36ad28',
 '2d1a8a0a-277e-476a-9ee0-a50eb242c7c5',
 '6f8bba69-5d76-4b1d-ab9e-e68f9b7d63a2',
 '25ae4940-83e5-442b-ba1a-40280f92fccd',
 '5c15ac67-63a5-44f5-a116-e845e129e0b1',
 '7376973e-04ff-4929-ac50-e3a44201154f',
 '90f99058-90ba-4d89-8e1f-74d75d87320a',
 '2e0e324d-ffe6-413f-8473-be5a2256b8f2',
 '9f3dec68-3bc6-4ae1-9853-58bd9d75872c',
 '53d59d1f-cc7d-4405-8e04-cf75e5abe555',
 '00cd68bc-89ca-4334-ae9c-b9c8c9109cda',
 '72dfe14e-ed4f-4cd6-8703-4cff3283bb54',
 '48cec86e-aa61-4150-bbce-9e5ce7ef60ef',
 '7c998615-4de9-4f26-922b-9134103b09ac',
 '95193a3c-3819-4964-a614-7fc37413fbd2',
 'f9ddf95b-92ee-4e85-9bb7-e42ec4126e8d',
 '616262c2-cf05-4179-9176-6b6d56d4a62e',
 'e3d50b05-4212-4123-be8a-91c930a769fc',
 '722c2152-3fda-43a2-a964-3aa6a802d696',
 'dcd68bc5-3d11-4e6c-a471-521b9b38d6c3',
 'cb224110-ae65-4084-9cd5-336e4a92bad4',
 '62e1cdb5-e371-46e8-8e2d-e12b67008727',
 '590e87ce-7fc5-471e-9a00-095af954a66b',
 '9ba4f564-6460-4c6a-bb24-1fc760765ace',
 'd6192941-eb42-473a-babc-a9cada41715c',
 '5eab8f06-eb7b-4460-a6a7-e0efc47570b4',
 'd1ea8284-57ae-4f3b-a19d-be9ce46f86f2',
 '28404eba-5027-4807-960a-8eb105b1991e',
 'c5925832-9d44-476f-bb26-59548d0794b4',
 'cc98b237-f366-4f00-8abd-3eef4a032abd',
 '0c327901-8ea8-4d8e-bf05-630bfdd63235',
 '8f4308d7-c7aa-4f23-ba17-c95a387eca2f',
 '2fcd7c1a-ff89-44da-8a2b-0af7fe4064d6',
 'f74139af-8be8-455f-8b4c-2efd6e56f530',
 '5aa0f858-35d1-405c-9583-0e19f59a4a2d',
 '2f655079-e694-498a-b35a-9b589472a588',
 'ac96a5ae-4300-4a1d-9be0-616621000b7b',
 'a3a39e85-5662-4272-a419-31bdaf2988fc',
 '992b670c-0b1d-439e-aa33-b9d939e7949d',
 'fa186f96-3d2f-4556-a6d2-a1f4930a6626',
 'f79dfe05-9ed6-499e-ab23-a8d930365223',
 'a3a436fd-0c14-4a8e-aa75-f69d08df9291',
 '2ba01ed6-6999-41cc-9827-5b37b9791581',
 '9850af31-597d-4b05-91e9-5b4100acfdaf',
 'd45f5639-29ae-472e-82e7-04c794361e52',
 '32b3ed37-768a-4070-84eb-984152e3a4cf',
 '583a14a7-5cce-4f61-b937-3557281e3374',
 '1f650161-6452-4a0e-a52a-051c1ff6b3d7',
 '9fa45b86-7354-43f6-897f-b36c05333dbf',
 '86f93650-d63a-4a3b-89c3-d0bc316414b2',
 'ceca569f-da4f-476d-9af1-98ce49cf6804',
 '20694dcb-5316-409a-bd1d-079aa3ef8df9',
 '1625a5b4-37ce-4c5b-9adb-db557415a142',
 '56f25d7b-360f-4624-b003-70e53a206c06',
 '6d3eed28-ed26-45cf-a2d8-d8e63b9cffd5',
 '7fc5b9c7-5ad6-4599-9f25-81dbec662e91',
 'c9e6fef5-7333-4e92-9849-607852257e27',
 '91367d17-00f2-49ae-9b51-95f1ba402bce',
 '53604a30-a021-491c-9001-8e2dab47fa4e',
 '7328d764-900b-4c59-bb38-4ed9b9681ffb',
 'e81e1f45-3ff6-43ff-b47b-bb028d03b772',
 '0dbb4410-1724-446b-a327-51b6c0eb911c',
 '0cf85e33-e9d7-470c-ba9b-bd7a7a551ead',
 '726310e6-94eb-41b9-a5c2-4b6b04996a76',
 'aae8e09f-8471-480a-b238-57d1aaef642d',
 '1a5b24db-6f58-4440-b7b0-d647191f0745',
 '68aeeb9d-c80f-4c1f-9790-7349b1fde4d7',
 'd32c4f37-3622-4973-8217-82f82bedc868',
 'd0e15ee3-6f99-4286-9078-230bff387bcf',
 '48fc9611-4ff2-4bf2-adc6-b1871edf7c1c',
 '3fcc381f-0dac-4cc2-8055-7376a57b08e9',
 '40333208-b134-4046-9ae5-8a6086112b29',
 '1924b69b-f797-4a37-8a03-10f7ddb5e8ef',
 'a8376a1b-b526-4646-ad7c-0a33d8dd232e',
 '9d34eb4e-a9bc-4513-b7da-a334dcd9de63',
 '1f8a1961-a05e-4444-ad88-2540e82c0de2',
 '22a3ec0b-9524-485a-9205-97f38a913e33',
 '4b8d0e55-76c3-4fb9-88a2-b532d88af095',
 '60b075b9-0682-4c87-a902-bf91c56cf821',
 'd180b87b-40f6-481b-9245-aaec0ab57285',
 '56eef24a-8b08-4095-9545-81d4a236f294',
 'a33c1c2b-7b3e-45d2-ac00-8cf4e8d2104e',
 '9b081108-0717-44b1-a302-6ebfcd992f54',
 'a8106b6a-9237-4d31-a3ed-3bb8eab27880',
 'cdb7f7f0-d654-4c16-a3ba-134d2d909e61',
 '1214e003-4516-4963-9c74-b6d2e5453225',
 '3bd2f75a-04d4-4e3c-b0fc-ebbc0c1bf9fa',
 '2cfcc23d-08af-44ce-a07d-4efb931e2c5c',
 'dc66ee63-f2fd-427c-addf-5749f2e75801',
 '2175dc5e-2ee7-4554-a959-a283eb0ce95b',
 '4333c53a-5ff2-4f52-b224-4b40a3843c49',
 'a178d200-bbd5-44ef-8a57-2a327f964926',
 '6de343b9-89e3-407c-a8c9-93f4b1acb271',
 'b842441a-79d4-4a65-b1e8-b7cfb47f3788',
 '13fb4d7d-f6c0-4312-889b-2b814aee9be1',
 '1be7a266-dc2e-4919-8577-c55160b886ec',
 '48283a7e-d51c-4aa8-ad19-6f35ee145566',
 '56d651fc-0c66-405a-bf3f-f03addcd1241',
 'b6351886-9ea5-4355-a33e-16e0c81e8e88',
 'c882bbe3-81e8-4182-b91a-d3c8aedd0b22',
 'a47ac6af-1481-4ce7-86af-894c28094a82',
 '1ba611c5-8315-4a7a-9eda-c18464b65078',
 'c33b2d47-c125-4a2f-9b06-f370d30ec7a7',
 '38b4724f-c291-4fbf-bcd6-6e148de7a1c4',
 '8f610748-e029-4132-823f-f04b8787358e',
 '18502d3a-f804-4808-810f-9656006c22ea',
 '40a1744b-e1d6-4d72-9227-ab7aff6cb589',
 'f2ce4ddb-50b8-4f6d-ae40-fd3926cee8f0',
 'ad635978-c67b-4a2c-bfa8-5d895b4d75eb',
 '591d62ab-9d26-4b61-87ba-cffe0116233e',
 'dd4dcbf4-cc9f-4416-8f72-bf5f279802f0',
 'f602fb2e-55f0-4181-9277-368fefc65374',
 '3980ebb9-ebc6-4ce3-b614-93ec962568ca',
 '842a6599-a675-44b7-9e65-bdce04d4b6bd',
 'df3ee10b-8053-463d-a9d6-ab513d345f1a',
 '3d16ec57-0d31-4512-87c4-a83305252b27',
 '7ca16f7e-3379-4fec-9109-9ada6cb4aa29',
 '4269afa9-add9-456d-b71a-2072b4a988ef',
 'dbdec7fd-1a2a-47a5-8427-ff4b63c980f2',
 '3576476d-cfdf-444a-abf2-de311ba32031',
 '4ee9ca68-8275-443e-912b-7ddafd4db39a',
 'd2fd1f46-88e5-4b40-86ca-bc2f09b43bc3',
 'e7a8c947-37ef-48a2-9e6b-75079ae96ddd',
 'd8f960ae-920f-45bf-88dd-ec7e20e636e5',
 '908cbc44-2460-48b7-8b9b-eebdc16b2466',
 '67d6d0d1-f13a-4297-84e5-285a1cd7ab8d',
 '8c6f694b-3d0a-4ede-a807-99226d89dee8',
 '5b3e7649-e67b-46dd-b5d2-8b941f154d98',
 'd07be023-aadd-405c-9a43-f4c135234436',
 '86891aff-df87-4691-a334-4b708e60073b',
 '45797122-b297-49f2-9cc5-f521519e3494',
 '11a2bc98-0440-4239-8d34-98a0ac3167bf',
 '5fd8462d-5e69-475c-bc0f-3cc0ac859ca8',
 'bb1c5ff2-e26d-4b92-886b-11548defa311',
 '2dc5e120-9074-44cb-b947-bfc53189dfad',
 '89fe493f-c4b7-4d11-b989-5c363e5cda66',
 'a51f4b0e-7ae7-4f70-8eff-652872ceda53',
 'b0985f8c-73a4-49ea-b8e3-497c7b8654c4',
 '4ac57d4d-26e0-43d4-b5f4-4a41222c9721',
 '04368f60-74f1-4391-8595-69d565febb6e',
 'ccd081cf-4572-4812-a6ef-385dea2d1562',
 'ada022c9-0249-4eac-ac9d-753af0df453d',
 'c6dffea7-72ab-461f-a038-fee9a4b98121',
 '0120f96b-3670-48e1-8648-4d39acde9cd4',
 '9b53d41b-5edf-4582-b33e-61b657e7dd30',
 '828901ba-9633-4f52-b2e5-8af76dc38343',
 'f770ac11-5c93-41bc-90cd-6cb673c8e195',
 '7e8175ee-5ece-4995-a74d-4cd29864fb05',
 '83c2cbdb-cc24-424e-a471-efa900d13fdd',
 'ad00f984-177c-4f2b-bd1e-8b983932d3d7',
 'b89ffefc-c4a1-4418-b9fa-865132b70010',
 '87d40c29-722e-4039-b10b-9368aeeff162',
 'f8b0055c-c0bf-4b7c-b0cf-afa4bd5c9124',
 'ee5fc619-59d4-44ab-9fdd-f258dfdee3dd',
 'df057251-a7ec-4ea8-a4a9-7238bb3d6f3f',
 'ce830a12-a44f-40ec-bac0-60589e5c261c',
 '3a6c5d66-0b79-4371-8629-9b4f60898c67',
 '3eaab87a-df4c-4823-bdde-a2ec3e3d9f72',
 '482aece7-1a77-4b62-b93f-48ccda07bc9f',
 '63791814-4014-40fc-8192-c92bde0bdcdc',
 '20210db5-983b-4ca7-b651-ce2488ed54d1',
 'd5ca40e5-0baf-42b9-9215-0f6a7405ee01',
 'a297f9d4-42ff-4509-b95e-3700fcc2d779',
 '07fd6a6a-21ab-423e-8007-375cb229aaea',
 '7fd22726-9903-4030-9949-ccc99a0fc27c',
 '3c8e0222-feba-43dd-b82b-de31521bc321',
 'bcba7fbd-f4ef-41e1-bce5-425de524888c',
 '99e762b1-0d44-49b0-b0c5-c052ed6cd518',
 'cef0a837-958b-4fb9-a73f-4c9ef34095dc',
 '5fe1fe1f-796b-4864-96b7-3107885bd40f',
 '3e26a52f-be33-4845-97a9-0e4b73babe78',
 'b2de03ea-fa81-43c8-b07c-df80677c9963',
 '18a9d01d-af60-4073-b9ec-a5dd5238a836',
 '24d4bf49-edd2-4682-be7c-8e11d4069b8b',
 '27f79052-9e8b-432b-8dd0-7e2426b7f163',
 '7b3dbded-b5eb-483a-868d-ba1172ab6723',
 '24a5b066-2f25-4d47-bdc2-82c1d7ddbaeb',
 '52cec0b3-24d5-4e82-a07d-2a40b0a3d923',
 'd11aa3fb-da55-40f7-bac9-3fbd59ea357c',
 '5620198c-5815-41f3-b7e6-8ea944160e5a',
 'af489746-25dd-4950-b58a-4a687ed6fd29',
 'b980e405-a215-4847-b320-106881fee860',
 'dad491ef-7be6-4e7a-8a9d-78ae75947fad',
 'c684aeea-d550-46a7-8261-d2b48a6da2a6',
 'f5fb9e7d-a072-4d25-8f94-a22d888924d1',
 'd776b267-0108-4107-9640-e83099bd2201',
 '81763a93-22e5-4c02-80ba-efa6050ed7a4',
 '016540db-6ec1-4500-92fb-0c9518a5dc6a',
 'bd9bffaa-7455-42c0-bfb3-97bbab82fc2e',
 'ff00bfeb-a08a-4104-9208-bf5762124360',
 'cbc3b2a0-941d-481b-80e2-ef3412b3a7f2',
 'ada6a8f2-e59d-4477-b484-0ff6829c15d2',
 '75c18eee-7b65-4b5d-981d-980009a70128',
 'beb4ec9c-f37d-4008-8e7d-051366d771f7',
 '8098c3ab-f239-46c7-9fa9-73b0d977a434',
 '10bb7e20-a525-4ea7-a9e0-37829cd26e92',
 '15010c98-bee6-430e-8f4f-a1945590a7b7',
 '6a24e80a-4c24-4064-b031-8302a3e406aa',
 '68600371-5a3e-4d67-ac3b-70be4b884e12',
 'f12520af-0efc-4993-94f0-9bb72abf370c',
 '4a25c2ea-d971-4887-86ad-ccc16a612084',
 '12fe68ae-cd3d-45ed-b14b-ff57a46be433',
 '265604f1-0a82-400d-a28e-2817dfa3aa48',
 'aee7ebbe-7548-4fad-a6fd-ab41ac4c8521',
 'cc380271-e92d-4f8e-9b1a-bd56aa50472c',
 'cbd0f656-8b89-453f-b424-bb0d6b5b7aac',
 '07a77b85-a1a8-482d-a5aa-e0b6ff0292f5',
 '4c7e9f62-cf43-45a4-8a1c-3916fba2a82b',
 'cfd16992-18f4-4d85-920f-63ae73ba99c8',
 'cbf67841-3025-4cfa-8470-b0de2dee391c',
 'ee08be61-2c84-4515-8f66-b28acd0ae68c',
 '4a58d394-6d61-479a-a407-42d653b7cd00',
 '223b9ec2-a5a9-4fae-bdc9-db46b529e0ce',
 'bc86d0f3-993a-4fe9-bb19-f1a2d9cffb86',
 'e37d69af-4862-4086-9ccf-4bd9ac159298',
 'aeddd088-5921-4357-a76a-4ab25f661709',
 '9daa3a42-276c-4d81-bd78-6ba807014ff7',
 '86df1e13-d192-498a-8072-8bcacc363a49',
 '67992301-d641-48b7-8b6d-cbb59a187da4',
 'fc95c8ca-7950-4729-b403-e40669fbf6c0',
 '65e33ec4-bada-4a18-b8c5-a7e7db0fb3ff',
 '20dbebc6-df73-4009-9397-a25f825117e2',
 'bf684eba-b117-4180-bbdc-1729dbde783f',
 'd84daba3-7d83-466c-a7a4-878a70725d20',
 'df76203b-6229-4b50-8f3a-adaa52168b42',
 '7c222172-59b2-469f-8f6b-226ceb553787',
 'b928f096-3bea-44d1-bbe9-38f6cf1926c5',
 'a9c64953-47db-4b4d-9c0b-89c9bbf97761',
 '066ab5fe-0934-4d86-a708-557355534cdf',
 '411e8669-9fd0-4b58-a4e6-add71b0eb27a',
 '88e3affd-b243-4573-8c90-0f5bb24d12b4',
 'e991f67b-8797-4817-a66e-b6c007568cef',
 'b401d1d2-2267-4eb3-a8db-06ba66540055',
 '03d89dd2-5fcf-4edc-b1bd-0a3ca37142e4',
 '1a95cf89-9f7a-4a60-a13e-d6c2abf8c456',
 '14229ccd-11b1-45a3-891a-ede1ea6832a3',
 '5b211833-eaec-43cd-ba38-75a4a71b8bdc',
 'f3f6ec23-2d41-4c8b-b703-88c161615db4',
 'f1a19e47-8c63-40e9-9427-e0f3e03d88b9',
 'fddb3d17-6e2e-4e19-8179-b5e15be90c0c',
 '8b2696bc-eff9-4d7b-858a-60b62e2ea0c3',
 '8c722a72-0353-4c39-bf85-08a4d218f092',
 '0cde4f26-9bac-4d66-8f97-d9d0f10e4a8a',
 '99b8ab39-c3f7-4d7d-87d5-c3e5b0f3427d',
 'e6a3024e-0c33-4332-9190-19fd6ee4142b',
 '16afdfd8-ea8e-4d57-834f-8cb714431b14',
 '8e0b4833-4ad7-45b7-a826-dda31995cb29',
 'aadaa69e-ed5a-4fb8-851d-d5adca900146',
 'c3b1d0f8-bb56-4f47-84ba-1493acd8b295',
 '6661ba27-5fe2-43c7-b215-a1532f266f35',
 'bf86beb6-5066-4477-abd2-88912ef70eb3',
 '5b2ab96d-8736-4be2-90f0-6602aee489ff',
 '68019de8-6a6b-4138-aac4-47eb4c326fc4',
 '0c484601-f0d7-4702-9be0-4f37ccd3ee19',
 '077e3372-64b5-4392-b97f-d68b2ba5cd03',
 '69b09e25-7eb2-4435-aceb-903749945865',
 '0976bc68-b6d5-4533-9adc-eb6675743acb',
 'e7dbe67d-fd83-4e2e-b2d5-a4689248f083',
 'c27dcb92-cdff-4b43-b04f-7b82c2ac3250',
 'f24b485c-66f3-4ba9-8090-4befe0ec5315',
 '2178f226-597a-4454-85fd-de0f53afd111',
 '0ea86133-6eb6-4761-9609-4fa912f5a283',
 '5224609a-1c86-48a5-aab7-f3cf7b930c67',
 '164c567d-2660-4373-b1eb-8e9c9cfb881a',
 '8046c3a1-3be7-4e70-9081-e49cdeb91bc4',
 '857625f3-fdb5-40e8-b53e-69e314b2f2e5',
 'd79a91a3-5526-4118-889c-e18845c69e36',
 'c1ccd850-59cc-4b11-aa26-06b2e7173d4b',
 '453ac6a6-ecfd-492c-b645-2242b58edd02',
 'cc621af4-80a0-4b74-b00b-a4f38c2f5ee9',
 '92bcaa7d-8256-411f-a705-87d7badd48a1',
 'a45e9e17-c9b8-4d6a-a214-8b93b3c6b151',
 '448f2803-8944-4773-9688-daec33c91d37',
 '9ec4df47-207d-4a82-a4d8-f75d06bac0c3',
 '5f70a09a-73a3-4883-b2d2-7c9f9a29dd58',
 '0f5594a0-98a2-46bf-8d6e-22e6bcd4dd99',
 '8ed93931-6351-48db-a057-b742474342d1',
 '55838687-5c4f-4ba9-9dd1-a7af1fa8b86d',
 '881c5414-640d-4fd5-8e6d-c536eb5556d1',
 '34f12074-ff8e-44c8-811a-840830cfc58a',
 'ae186673-e540-4785-8795-2c29a8ec4d01',
 'dbd15d7e-58a6-409f-bc2b-5ea5faeb24cf',
 'c755feda-0ce2-41b8-9d91-872b3cc5d42f',
 'd3de0acf-4362-4fff-8e46-7e284935ab7a',
 '9b576f6b-5e4d-454e-a11f-50ed98d6e843',
 'c12946a6-0ad3-41a0-9103-445ff69d0a03',
 'e2a4e7bd-06fd-45cb-bdcf-cebdb22bc13d',
 '156edd9e-5373-48c5-9497-061b51006a45',
 '5dbb64c3-bd6c-4e9c-a93f-25c6197219b0',
 'f1a5b318-a4e3-4ab8-afba-9009c9de35cb',
 '48a769f9-44b2-4dac-b097-cb7f650bc492',
 '278e0ae1-b4af-49aa-a3af-ec8cc52195b6',
 'f550b848-855c-4433-8cc7-21fd5476bc35',
 'bc007612-907d-48db-98a4-057f2f2e6c5b',
 'de859275-0680-4ae5-b46e-bb352cd38f8e',
 'cb2597ef-af3a-4e42-9ad7-4620b43b875f',
 '41fb7965-fa82-4f35-8080-15b0cc4f8c7e',
 '630d29d7-ab3c-4de9-a4f2-5ef36403825e',
 'dc040ee3-6a93-4c9c-8c5d-340e9c2031ef',
 'd047f80b-3998-457a-88b3-641054dd9e59',
 'be8cb297-7146-4c89-89c7-402d99d40df6',
 'cf633ca6-c8a8-4081-ac2a-d115d0d7a0f6',
 '337822d7-3873-407d-8b91-d35ce325143a',
 '0930cf0a-72d9-4d1c-91af-b54742c1b8da',
 'd78df5a8-a44d-4f44-82c3-f059a5fa2c72',
 '4fa61bb3-66af-4309-9721-12aabea8e4bf',
 'a8891818-b9ff-417d-b4f3-fc7e22954a3c',
 '53f6bcda-afac-4c41-b204-e8348716d87f',
 '8e20a133-b789-4522-a4ae-34e48948abdb',
 '61e7db11-3d67-407b-a144-8a35172c479b',
 '23fb784c-b836-4435-b69e-a9f9a3c1fe80',
 '8e8be46b-2ac6-49ee-81e7-6997c3eac927',
 '0ae120a7-9042-48ed-a3e9-ddb35c7f6b50',
 'a841c11c-8eef-4854-ba5d-ecb36619f34f',
 '7e964e37-8300-4550-bf8f-e5017b390fd6',
 '83eb40cd-2e37-4b14-9109-2cdf39e05833',
 'bb972970-ff8c-4585-9330-2c7cc665dae0',
 'a295e218-4eb9-4af3-9474-2ce6ab629a84',
 'c7a8e6a9-2b5a-4abf-b0cd-152f3b9de2dc',
 '2fc2629b-7e52-4ee6-815b-b2ebefe2c909',
 '462c61b3-f841-4efe-89a7-43ce6d735334',
 '9f04462a-fe5a-4b47-aad8-051afe3514a0',
 '0a314676-62a0-4822-9010-cab4969e056e',
 'f0c559c4-a876-4c87-8b8e-d5224b346501',
 '1c608370-1840-4bca-a27e-88900ef4ffe5',
 '843bfbe4-3403-49be-af79-f34c1c59a826',
 'f899bfbe-d6c2-4276-8168-07c190f31a90',
 '0a780b55-881b-4d15-93b8-d0ba1d7b836c',
 'de62321c-1b14-4ab5-b67d-315602d882db',
 '49a094a0-2d19-41b5-9e21-ee9969f416bb',
 'f1808cd6-8808-4678-a4f4-bb69eb523475',
 'd408fa25-381a-4bd6-b2d0-977e3e29fc99',
 '6ff1faa2-294c-46b8-bf64-c2c68e97fb15',
 'a1d43f8b-0cf9-4f0d-9f4f-fa0187a6e4c5',
 '776df5fd-3dbc-4285-bd4b-dd8a4dc7cbf4',
 'c21623d4-3e19-423f-a523-97f7d3d8e615',
 'c2df3b65-9e23-4ab9-bfa4-a5de40bedfb7',
 'b1a4572f-91ff-4d72-b315-112fc9707dfb',
 '44fbcbae-7f9a-489c-a83e-257a116509c3',
 '8c8f6057-0bc6-4570-91d7-c79bdc8972d2',
 '6d57bf37-35d4-45d7-8ad2-59a8ee1897e5',
 '47092fb7-6c21-4efc-9c21-85b29372682f',
 'dd02268e-4a20-4e03-b2ff-527e86ecf5e8',
 'b8fb7d6c-e9e6-4e63-b843-3f532fbaee14',
 '3366a9ab-d58c-47cd-987a-abf95887452b',
 '12795cfc-2ce0-4db2-b986-0aaf8b4d354f',
 'f9ef595e-8f13-45c2-a438-b86eb5d377d5',
 '08e5c2ee-4754-4a32-a5fc-71dbd385272b',
 '43eb0849-4773-429c-b632-6efe3e4f07f0',
 '5dbd1fec-c2a2-4bb0-a256-1de494a3a01c',
 '1c549933-7a4c-49fa-80bc-837e789eed77',
 'd86d6112-1fe8-4966-b477-c801e640d6f8',
 'cc7e7c05-dd6a-4e8d-8be8-f6a7dc24ce53',
 '4392bf05-a787-489b-a2f9-5c330ce043e9',
 'd7f92539-8a55-4c5e-9f31-c216969cde73',
 '1c4f3670-96ff-4bf0-9a6a-6aebd8ba5d76',
 '1cc5ffd3-f60f-4d9c-8e5e-70f3a28bff0f',
 'b5a47b26-4dab-4a95-9315-dfa5d1944013',
 '60793d2c-adf2-4715-8504-dafa1a53e4c8',
 'a053d6ae-aad7-461d-a970-7e56abbeddf7',
 '26fdff19-c4bd-4324-85fe-6229f04e2196',
 '9acb38ed-434c-4f6c-916e-8828c71c6bac',
 'ca5bfd0a-60a3-4db1-961d-78903607d55c',
 'f1867630-231f-489e-b59d-33b457dd36dd',
 '0b78df4e-4d57-43c1-bad2-4ed1eb8b8ea0',
 '19a84e6c-783f-451a-ac73-31533a0a465c',
 '6f15042d-fd6e-4ab4-a230-fe4d420481d7',
 'd5ee10bf-1744-431d-b148-939a51c75f77',
 'eac16120-9dda-439b-8bc7-0e04f34e3c79',
 'ed9f88ef-c755-415c-802b-e30cdb0d22e0',
 'e813c2fa-5a93-42c1-ac02-b11269fb84e1',
 'd5f7dec5-eaba-4a04-ae22-d921e98e7386',
 '215e6adb-a180-4634-a742-37caa824772c',
 '526ca4e9-1174-4f53-9364-96fe33ec72e1',
 '8ca4ca04-6e0c-4321-be5c-53f39f2a3050',
 'c70ebc1f-f607-4863-bbe0-7def394ff9e1',
 '2570f678-3c08-488d-89cc-06d0e0471f4c',
 '5b4588b3-4f44-42ce-a83d-45aa65be8210',
 'd30bed32-3bcd-4216-8dd5-6f6887d02092',
 '70ba7588-bf16-4a31-a410-40759e740bbf',
 '311a0ee8-4be0-4ab7-a9f2-e253bf8c3d4a',
 '71c8bce9-2cdc-4c48-a375-9dec3a26900f',
 'feb81d63-ef8b-44fe-937d-e881a950de77',
 '2f2b4789-2692-4cdc-bf15-811123c4b9ed',
 'a00285ea-f5e2-49a4-985f-3b6600ce9959',
 '026341ac-792a-4dca-9480-bf76f3f64778',
 '63a69996-8734-40db-9773-3b3db755886b',
 'e23f7c02-0283-41a4-9007-5f9aae57d3d3',
 'f5d229fd-25d0-420b-a1df-69ccc909c47d',
 'd17fe8c2-ce36-4d1b-86bd-d3d71df17c2c',
 '9a474743-cc29-4bd1-9753-2d6bc538f39d',
 'f08c8310-9260-4908-ab1e-107a4eb1d1c9',
 '61e675df-5d34-441a-8bb8-65ac35c3de9b',
 'b1e85441-71ab-46df-b83b-1303fd658945',
 '7be975c3-10bf-4f8e-aded-f5a98f33de8e',
 '5a5ad48c-b8f5-495c-96e6-f9ac8ea4ed65',
 '9a56ee12-a7b1-41f0-bede-917067f9955a',
 'f0456a13-4eb3-43a4-ad97-9ed012f71e1b',
 '7e2a7a10-478d-4406-8a03-c1174ab40a85',
 'd6f8d5c1-9f35-4626-bacb-88faa3e9461c',
 'df17c971-9264-459f-b299-2c793b6ace91',
 'db97c01b-12d2-484c-80f3-18da6d00c8ae',
 '7dcaa9b0-cdbe-4d59-b5ba-4ce53693a11c',
 '86d2d4dd-6334-444f-adff-92b09860af3a',
 'b27c4ce2-7ce8-463d-9e68-480894ab7864',
 '7bb5b840-7cae-4e7f-946f-32b8e3d405c5',
 '75857ddd-7295-4588-a814-63c4598948cc',
 '536a98fb-9d08-442e-bdbc-adc5677cce73',
 '36884d6c-d44e-40be-9ea2-5e8c862a307f',
 'ab4e9260-d349-4cb1-9722-da89846d1be6',
 '3690567f-fa3c-4f05-8687-62e042a44706',
 '5c1cd964-57af-49b3-91b5-c4ac1691ca86',
 'a9b03df3-baa9-4e90-a2f6-6377d6c95c90',
 'd4f3d7c7-093c-4aa3-9d4b-9d7101ee3400',
 'acb001d0-8474-4aa3-b2c5-72f039b56154',
 'b29f7a52-1f17-4b39-9c2a-47f758648ecc',
 'cb492b4a-aa96-4c4e-8f51-a4fccf66efd5',
 'e558a2c5-937b-48bb-8ee9-ae370da04d0e',
 '8a5ca35f-bc11-4e44-8ea6-f8e2ab0f8a54',
 'd49c6aa9-9a90-4b51-b31b-099e74172e4b',
 '5374f8d4-71cd-4f1d-accf-fae14861a87c',
 '04bec52a-9bab-4075-b058-caa37a1319f3',
 '8f707ef9-d086-4468-a6bb-a31d971c4721',
 '20b2bf0d-9651-44c4-a2a9-b0e84f3663de',
 'debf1ade-2f01-4e1f-bf39-07fd9d19a9d8',
 '89f6b12e-19c9-478e-8873-e0b55af27858',
 '6c7935b8-dd96-45b1-a0a7-e1ee7ad106c8',
 'faac17a7-8b8a-4a00-9394-1b0aef93b3ec',
 '7bc67e26-d97a-41e3-8168-acba1d592629',
 'e63e11fb-b704-440d-9b4e-b9128035c728',
 '3eac4eda-fdeb-4062-89f6-d7442faeb8c7',
 'c610f15f-6ee7-4891-b5a1-3c34daec7575',
 '84762d6c-2910-4bd3-adce-f8e15e494dfd',
 'b7788f94-6984-4845-b719-00897213b9f5',
 '006bdefd-aa86-4b7a-b45c-399e8458f08c',
 '67e1e878-afc6-4911-aa4e-9acc662b7f91',
 'd25dcdd4-4d47-45e4-98e8-35795e5022b0',
 'd673ac32-6f9d-467d-9cd4-abec0abf59ee',
 '79995d56-410c-417b-be19-d68e596d91a2',
 '1a09fcdb-924d-4bec-911f-4719255deaed',
 'ba935d2f-942e-4109-a66b-fa1870fa6c12',
 '2476fda5-1ba7-43d5-89ea-d9b6deb756f6',
 '53f8a952-9251-4e70-84f7-c4ea1be405ce',
 '722458c8-abb2-467b-abb4-7c8f281b284d',
 '3c6f2bb2-bb15-4408-9aab-aad9c7a57e63',
 'd5da1db5-861d-4a59-8561-546e210b575a',
 'f889c467-559e-43da-a3f2-7e7dcb1420fb',
 '973d7f38-b0b5-4da6-a0e2-f0dcc2235bd3',

#### Saving Vector Store

In [39]:
documents[0]

Document(metadata={'faq_id': 0, 'source': 'AHCCCS', 'url': 'https://www.azahcccs.gov/AHCCCS/AboutUs/covid19FAQ.html', 'language': 'en', 'type': 'Question', 'chunk_id': 0, 'dataset': 'COUGH_FAQ', 'embedding_tokens': 55}, page_content='Question:  Does AHCCCS have a centralized resource for medical coding resources related to COVID-19?\n\nAnswer (Part 1): Yes, the AHCCCS Medical Coding Resources webpage includes a COVID-19 Medical Coding Information section and COVID-19 Emergency Medical Coding guidance.')

In [40]:
vector_store_path = os.path.join("/content/drive/MyDrive/MS-LJMU/Vector-Store", "Store-3-3072-COUGH-FAQ-ENG")

In [41]:
vector_store.save_local(vector_store_path)